/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LAB2345;

/**
 *
 * @author LegendNguyen
 */
public class LAB2345 extends javax.swing.JFrame {

    /**
     * Creates new form LAB2345
     */
    public LAB2345() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Ho = new javax.swing.JTextField();
        txt_Ten = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_TenDem = new javax.swing.JTextField();
        cbc_NamSinh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_SoGioDay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_MaGiaoVien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_SoGioDay1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_BangGiaoVien = new javax.swing.JTable();
        btn_ThemGiaoVien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ĐĂNG KÝ TÀI KHOẢN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Họ:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        txt_Ho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Ho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_HoMouseClicked(evt);
            }
        });
        txt_Ho.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_HoInputMethodTextChanged(evt);
            }
        });
        txt_Ho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_HoKeyPressed(evt);
            }
        });
        getContentPane().add(txt_Ho, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 221, -1));

        txt_Ten.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_Ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 221, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tên:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tên đệm:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txt_TenDem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_TenDem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 221, -1));

        cbc_NamSinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cbc_NamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 221, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Năm sinh:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txt_SoGioDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_SoGioDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 240, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Nhắc lại MK:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Mật khẩu:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        txt_MaGiaoVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_MaGiaoVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 240, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tài Khoản:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        txt_SoGioDay1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_SoGioDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 240, -1));

        tbl_BangGiaoVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tbl_BangGiaoVien.setShowGrid(false);
        tbl_BangGiaoVien.setShowHorizontalLines(true);
        tbl_BangGiaoVien.setShowVerticalLines(true);
        tbl_BangGiaoVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_BangGiaoVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_BangGiaoVien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 720, 292));

        btn_ThemGiaoVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ThemGiaoVien.setText("Tạo Tài khoản");
        btn_ThemGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemGiaoVienActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ThemGiaoVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 200, 46));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_HoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_HoMouseClicked
        // TODO add your handling code here:s
    }//GEN-LAST:event_txt_HoMouseClicked

    private void txt_HoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_HoInputMethodTextChanged

    }//GEN-LAST:event_txt_HoInputMethodTextChanged

    private void txt_HoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_HoKeyPressed
        //        txt_MaGiaoVien.setText(txt_Ho.getText());
    }//GEN-LAST:event_txt_HoKeyPressed

    private void tbl_BangGiaoVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_BangGiaoVienMouseClicked
        //         int temp = tbl_BangGiaoVien.getSelectedRow();
        //         txt_MaGiaoVien.setText(arrayListTeachers.get(temp).getTeacherID());
    }//GEN-LAST:event_tbl_BangGiaoVienMouseClicked

    private void btn_ThemGiaoVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemGiaoVienActionPerformed
       
    }//GEN-LAST:event_btn_ThemGiaoVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAB2345.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAB2345.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAB2345.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAB2345.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAB2345().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ThemGiaoVien;
    private javax.swing.JComboBox<String> cbc_NamSinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_BangGiaoVien;
    private javax.swing.JTextField txt_Ho;
    private javax.swing.JTextField txt_MaGiaoVien;
    private javax.swing.JTextField txt_SoGioDay;
    private javax.swing.JTextField txt_SoGioDay1;
    private javax.swing.JTextField txt_Ten;
    private javax.swing.JTextField txt_TenDem;
    // End of variables declaration//GEN-END:variables
}
