/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LAB5_KiemTra;

/**
 *
 * @author LegendNguyen
 */
public class KiemTraLab5 extends javax.swing.JFrame {

    /**
     * Creates new form KiemTraLab5
     */
    public KiemTraLab5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txt_MaGiaoVien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_SoGioDay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_SoGioDay1 = new javax.swing.JTextField();
        btn_ThemGiaoVien = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_BangGiaoVien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tài Khoản:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        txt_MaGiaoVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_MaGiaoVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 240, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Mật khẩu:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txt_SoGioDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_SoGioDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 240, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Nhắc lại MK:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txt_SoGioDay1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_SoGioDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 240, -1));

        btn_ThemGiaoVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ThemGiaoVien.setText("Tạo Tài khoản");
        btn_ThemGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemGiaoVienActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ThemGiaoVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 200, 46));

        tbl_BangGiaoVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbl_BangGiaoVien.setShowGrid(false);
        tbl_BangGiaoVien.setShowHorizontalLines(true);
        tbl_BangGiaoVien.setShowVerticalLines(true);
        tbl_BangGiaoVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_BangGiaoVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_BangGiaoVien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 770, 210));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("4.Check lỗi để null các ô textbox (1 điểm)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("ĐỀ THI LAB 5");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Viết 1 chương trình đọc dữ liệu từ file lên và lưu xuống file");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setText("1.Thiết kế được giao diện (1 điểm)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("2.Load được dữ liệu lên từ file và đổ vào bảng (4 điểm)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel10.setText("3.Thêm được dữ liệu mới đổ vào bảng và ghi vào file (4 điểm)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("ĐĂNG KÝ TÀI KHOẢN");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemGiaoVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemGiaoVienActionPerformed

    }//GEN-LAST:event_btn_ThemGiaoVienActionPerformed

    private void tbl_BangGiaoVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_BangGiaoVienMouseClicked
        //         int temp = tbl_BangGiaoVien.getSelectedRow();
        //         txt_MaGiaoVien.setText(arrayListTeachers.get(temp).getTeacherID());
    }//GEN-LAST:event_tbl_BangGiaoVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KiemTraLab5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KiemTraLab5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KiemTraLab5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KiemTraLab5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KiemTraLab5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ThemGiaoVien;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_BangGiaoVien;
    private javax.swing.JTextField txt_MaGiaoVien;
    private javax.swing.JTextField txt_SoGioDay;
    private javax.swing.JTextField txt_SoGioDay1;
    // End of variables declaration//GEN-END:variables
}
